insert into menus (name, foodtype, vendor_id, price) values ('Pork Roll Egg and Cheese Sandwich', 'Breakfast', 3, 4.45);
insert into menus (name, foodtype, vendor_id, price) values ('Sausage and Cheese Sandwich', 'Breakfast', 3, 4.45);
insert into menus (name, foodtype, vendor_id, price) values ('Oatmeal', 'Breakfast', 3, 1.60);
insert into menus (name, foodtype, vendor_id, price) values ('Muffin', 'Breakfast', 3, 1.50);
insert into menus (name, foodtype, vendor_id, price) values ('Omelettes', 'Breakfast', 3, 4.00);
insert into menus (name, foodtype, vendor_id, price) values ('Pork Roll Egg and Cheese Sandwich', 'Breakfast', 3, 4.45);
insert into menus (name, foodtype, vendor_id, price) values ('Sausage and Cheese Sandwich', 'Breakfast', 3, 4.45);
insert into menus (name, foodtype, vendor_id, price) values ('Oatmeal', 'Breakfast', 3, 1.60);
insert into menus (name, foodtype, vendor_id, price) values ('Muffin', 'Breakfast', 3, 1.50);
insert into menus (name, foodtype, vendor_id, price) values ('Onion Rings', 'Sides', 3, 2.00);
insert into menus (name, foodtype, vendor_id, price) values ('Jalapeno Poppers', 'Sides', 3, 2.00);
insert into menus (name, foodtype, vendor_id, price) values ('Pizza Fries', 'Sides', 3, 2.00);
insert into menus (name, foodtype, vendor_id, price) values ('Fried Shrimp', 'Sides', 3, 2.00);
insert into menus (name, foodtype, vendor_id, price) values ('Soup', 'Sides', 3, 2.00);
insert into menus (name, foodtype, vendor_id, price) values ('Chicken Cheesesteak', 'Lunch', 3, 7.00);
insert into menus (name, foodtype, vendor_id, price) values ('Chicken Quesadilla', 'Lunch', 3, 8.00);
insert into menus (name, foodtype, vendor_id, price) values ('Calzone', 'Lunch', 3, 6.00);
insert into menus (name, foodtype, vendor_id, price) values ('Stromboli', 'Lunch', 3, 6.00);
insert into menus (name, foodtype, vendor_id, price) values ('Tuna Wrap', 'Lunch', 3, 5.50);
insert into menus (name, foodtype, vendor_id, price) values ('Bacon Cheeseburger', 'Lunch', 3, 5.75);
insert into vendors (name, location, email, phone, username, password) VALUES ('Chicken Heaven', 'Montgomery and Liacourous', 'chickenheaven@hotmail.com', '2155555555', 'chicken', 'chicken');
insert into vendors (name, location, email, phone, username, password) VALUES ('Insomnia Cookies', 'Montgomery and 13th', 'iheartcookies@hotmail.com', '2155551234', 'cookie', 'cookie');
insert into vendors (name, location, email, phone, username, password) VALUES ('Crepe Truck', 'Norris and 13th', 'CookinCrepes@hotmail.com', '2151234566', 'crepe', 'crepe');
